### ISSUE TITLE
escape key to open menu bar and some links-compatible key commands

### ISSUE THREAD

**Issue by rcampbel3** [browsh-org/browsh#119]
Hi,

I absolutely LOVE text browsers like Links, and was just recently lamenting that none of them supported a modern rendering engine (but I was thinking webkit...). Thank you for your work to bridge this gap!

Anyway... my initial experience has been that the rendering is a bit slow (I even built alacritty to get GPU accelerated terminal) and that it's sometimes hard to tell what's going on with keypresses in browsh.

I would like to see escape key pull up a menu with shortcuts to commands with escape key press -- like in links.

I also like being able to use arrow keys to move between links in links and then "click" it with enter (so I don't need to use mouse). Would it be possible to support the same thing, be able to "highlight" the currently selected link, and then use page up/down for scrolling?

**Comment by tombh** [comment]
Oh I forgot to put it in the docs, but `CTRL+?` opens the documentation. So that's one step in the direction your asking?

You might like to follow the Vim mode issue for updates on navigating by keys: #31 

I'm afraid rendering is always going to be a couple of hundred milliseconds slower in Browsh as it still has to render in headless Firefox first and then Browsh has to in turn extract the formatted text. You see Browsh is primarily designed to be run remotely where there is fast internet, then people who have slow internet locally then only need to download a highly reduced text version of that same page.

**Comment by battaglia01** [comment]
I don't get to any documentation if I hit CTRL-?, or CTRL-SHIFT-?, or anything like that. Is there something I have to do to get this working? F1 does open the main brow.sh page though.

I'm running browsh 1.2.3 on KDE Neon (built on Ubuntu Xenial)
