### ISSUE TITLE
Adding suppurt for armhf

### ISSUE THREAD

**Issue by ChananelDavid** [browsh-org/browsh#134]
I am running gnu debian on a mobile phone
The system have 'armhf' architecture.
I like if you can support this
Tnx

**Comment by tombh** [comment]
Can you not use any of the binaries from here? https://github.com/browsh-org/browsh/releases

**Comment by leshniak** [comment]
armhf is not armel nor arm64.

**Comment by tombh** [comment]
These are the ARM architectures that Go supports: https://github.com/golang/go/wiki/GoArm#supported-architectures

Which one would you like?

**Comment by tombh** [comment]
Ah! I understand now, this is just to do with the `.deb` syntax, not how Golang builds.

So I'm using https://goreleaser.com/ to build the deb files and I assume it has a reason to `armel`, if I just replace it with `armhf`, am I just going to get another similar issue from someone else saying, please support `armel`! I mean the fact is I just don't know what the difference is between these 2 architectures is. Maybe I can use `armel | armhf` like is done in the `Depends` key?

**Comment by parkerlreed** [comment]
armel is really old to be honest. armhf should cover anything that this would be run on.

**Comment by MikuroK** [comment]
armel software will work on armhf hardware. armel is for armv4+ cpus with no hardware FPU, while armhf is for armv7+ with hardware FPU.
It's not completely dissimilar to comparing 'i386' and 'i686', with the former working on the latter, but the latter can make use of new cpu features. not many people make i386 builds anymore because most software won't be run on pre-i686 x86 cpus anyway, the same argument can be said for armel/armhf, if your software wouldn't run well on pre-armhf cpus, then it might not be worth making an armel binary.
At least as a client, this does seem like the kind of software you'd want to run on old hardware, so there quite possibly will be people complaining if you drop armel.
To give you an idea of "how old", the first Raspberry Pi models were armv6, so cannot run armhf binaries. so really, that's not terribly old.

**Comment by tombh** [comment]
Has anyone tried any of the latest releases?

**Comment by aquaminer** [comment]
@tombh checked `browsh_1.4.10_linux_armv7.deb` on Orange Pi PC plus (armbian) everything works, thanks!

**Comment by ProDigit** [comment]
Any news if this works on a Pi?
Looking for an alternative between Lynx, and Midori.
This seems like it could be the way to go on the Pi Zero W. (Broadcom BCM2835 SoC with Arm1176JZ I think)?
