### ISSUE TITLE
navigation

### ISSUE THREAD

**Issue by and09** [browsh-org/browsh#154]
Is possible to add normal vi keys for navigation?
^ begin $ end
number click link etc.

like https://fanglingsu.github.io/vimb/

**Comment by tobimensch** [comment]
There's already an issue for this. #31 

Short answer: Yes
Longer answer:
Someone needs to do the work.

**Comment by letarg0** [comment]
no this is not #31 
look at link
numbers are links

**Comment by tobimensch** [comment]
@letarg0 
Clicking links by using keyboard navigation is part of #31. It may not necessarily work using numbers, however home row keys like in vimium will probably used. It could be an option to use numbers as well. But the basic implementation of this feature would be ready, once #31 is implemented.

Another approach would be to fully support extensions like vimium and others like it, letting the user choose what he likes best. You can already install extensions by copying their XPI file to the browsh firefox profile. The problem is that browsh in tty mode currently can't forward all input events, so that those extensions would work normally.

I still think this is basically the same as the vim mode issue, the only additional request you two have is to use numbers for links. You can add a comment to #31 about this.

@tombh 
Was it wrong to close this issue?

**Comment by tombh** [comment]
@tobimensch Yeah It seems right to close this. Unless @letarg0 can give a bit more detail?
