### ISSUE TITLE
Mouse wheel support

### ISSUE THREAD

**Issue by eMPee584** [browsh-org/browsh#157]
Well, wheel scrolling would be nice.

**Comment by tobimensch** [comment]
Agreed.

**Comment by j-rewerts** [comment]
@eMPee584 What terminal do you use?

**Comment by j-rewerts** [comment]
I've found Nano on MacOS/Terminal has really nice scroll support. I've rehosted Nano [here](https://github.com/j-rewerts/nano) and I'm looking into how they did it.

**Comment by j-rewerts** [comment]
Seems like Nano has 2 modes:

1. Mouse support
This allows you to click in the terminal window and have the cursor show up where you clicked. I think there are other features as well, but this stuff Brow.sh already does.

1. Disable mouse support
Confusingly, this is the mode we're interested in. If Nano is in this mode, I can scroll the cursor through any document. Worth noting that scrolling actually causes the cursor to move in this mode.

So we want a little of 1, since we need to know what users click on and a little of 2 so we can scroll probably.

**Comment by tombh** [comment]
Yeah, so we already detect all possible mouse events, it's just that not all of them are acted upon - namely the up/down scroll events in this case. So we do have your 1. already and I think fixing 2 will actually be pretty easy as we already have code that reacts to up and down arrows, so the scroll events just need to be plugged into the same functions as them.

**Comment by j-rewerts** [comment]
Awesome! I'll look at it tomorrow.

**Comment by tobimensch** [comment]
This feature should work with the next release. v1.4.13
