### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by SAUCYSOUP76** [browsh-org/browsh#249]
How do i compile from a fresh arch install?

**Comment by tombh** [comment]
Don't you just want to use the AUR? https://aur.archlinux.org/packages/browsh-bin/

**Comment by SAUCYSOUP76** [comment]
Sometimes the AUR can be a hit or miss, i like to keep some options open. Doesn't matter now as browsh is a horrible solution to web browsing on a tty session.

**Comment by tobimensch** [comment]
@SAUCYSOUP76 
That's not what I'd call constructive criticism. If this is how you conduct yourself, please stay away from Browsh and its community. Tom put a lot of work into Browsh in his free time and provides free services on top of it at his own cost, and Browsh is definitely not a horrible solution. It does have areas in need of improvement, but I could create a cool demo using Browsh right now if I wanted to. A demo that no other terminal web browser could match. There are multiple development guides for Browsh, one for Linux users, if you want to compile it manually, that's one option you have. If you continue with your current tone, I'll be happy not to have you among the Browsh users.

**Comment by SAUCYSOUP76** [comment]
@tobimensch Ok remove me. Doesn't change the fact that text and graphics are unviewable in a tty using the framebuffer. If you don't like brutal honesty then that's your problem.

**Comment by tobimensch** [comment]
@SAUCYSOUP76 
> Ok remove me.
I'm not going to "remove you". I like the freedom of expression a free society enables us all to have. I was just stating my dislike for the way you are expressing yourself.

> Doesn't change the fact that text and graphics are unviewable in a tty using the framebuffer.
This doesn't make sense. There's no "framebuffer" in the tty. The tty has monospaced text by definition, and depending on terminal support there can be colors or styles like italic/bold. Browsers like browsh, elinks, lynx or w3m, aren't supposed to show you graphics, that's not what they're meant for. Why should text be unviewable in the tty? This is a nonsensical, so either you're clueless or you're trolling. tty stands for teletypewriter, it's all about receiving and showing text information.

> If you don't like brutal honesty then that's your problem.
In fact I do like brutal honesty. However you're making nonsensical statements, like text being unviewable in a tty interface. How should I perceive such a person?

The fact that I've used Browsh to read articles on websites like arstechnica and osnews makes all of your prejudiced (or maybe even trolling) statements look utterly ridiculous.

Even if Browsh isn't for you for whatever reason, why do you have the arrogance to claim that it isn't useful for other people, who may have vastly different needs and experiences from you.

**Comment by tobimensch** [comment]
@SAUCYSOUP76 
"I use arch soley in a tty session"
You mean you're using Browsh on a console limited to 16 colors? There's a fix to make it work there, which is pretty simple in fact. It'll probably work in an upcoming release. Like is clearly written in Browsh's documentation, currently Browsh requires a terminal with true color support to work.
I've used Browsh in 16-color mode on a Linux tty myself, I needed to change only one line in the code.

"I have not claimed that. You are putting words i did not say, that is toxic behaviour."
Toxic behaviour is something you're very familiar with. Isn't it obvious to you, that the stuff that you've written here is not constructive criticism, but rather offensive in nature? If you had written, that something doesn't work for you, we would've taken that seriously. If you would've described the issue in detail (bug report), somebody might have been able to point out how you can work around the issue, or we might be able to provide an update. However, you can't call a something a "horrible solution" without giving any specifics, and then expect to be met with sympathy.

Here's what you've written previously:
"Doesn't matter now as browsh is a horrible solution to web browsing on a tty session."

You wrote that "browsh is a horrible solution to web browsing on a tty session", this sounds very aggressive and appears to be an absolute statement, this can only be interpreted that you think it's completely useless. Or do you  honestly want to pretend that there is a reasonable interperation of this sentence that suggests that you meant it's only horrible for you? Even then, why do you have to use such offensive language? Github's issue page is like a work place, not like private chat.

"You appear you also can not take criticism."
I definitely can take criticism. By the way, I'm not the author of Browsh, so I've less reason to be offended by your toxic behaviour (thanks for offering the perfect description for what you're doing here) compared to @tombh. You're not offering criticism however, you're simply saying that a software product that is free and open source is "horrible" and you've only given one nonsensical reason for it. Valid criticism would be to explain what you tried to do with Browsh in detail and in what ways exactly it didn't work.

**Comment by SAUCYSOUP76** [comment]
@tobimensch 

> this sounds very aggressive and appears to be an absolute statement

That's your own biased interpritation of what that means which you have taken out of context by jumping to assumption.

Do you get a kick out of bullying autistic people?

**Comment by tobimensch** [comment]
@SAUCYSOUP76 
> Do you get a kick out of bullying autistic people?
Do you get a kick out of provoking people? @tombh tried to help you with his comment, you could've kept it nice, but then you call his project "a horrible solution". Now you insinuate that I'm getting a kick out of bullying autistic people. I must admit that your behaviour here has seemed very odd to me, to the point that I believed you to be a troll. Your indirect admission of being an autist does explain your behaviour somewhat, although I assume (and hope) that you don't represent the typical autist. Are you playing the victim card now? Or is being an autist an excuse for writing whatever you "feel like" without expecting consequences?

> That's your own biased interpritation of what that means which you have taken out of context by jumping to assumption.

So what's the non-biased interpretation then? Didn't we all agree to use the same language? My first reply for you got a thumbs up by @tombh and @parkerlreed. I've no affiliation with @parkerlreed , I don't know who that person is. Do you think it's a conincidence that we're all disagreeing with you?

What do you get out of this whole discussion?

By the way, I had absolutely know clue that you could be autistic, as statistically people that have autism are a small share of the population, and you come across like a person that could possibly have anger issues.

**Comment by SAUCYSOUP76** [comment]
@tobimensch i have not said one horrible thing to you and you have called me arrogant etc. I will never be using this software and i am glad not to be apart of this "community".

**Comment by tobimensch** [comment]
@SAUCYSOUP76 
> i have not said one horrible thing to you and you have called me arrogant etc"

I've judged you not only on the responses you gave directly to me, but also on those you gave to others. You justified your harsh words with your, quote, "brutal honesty", and your behaviour in sum comes over as arrogant. Is this too much brutal honesty for you?

By the way, you said these things to me, which are horrible (and slightly amusing, because you're apparently unaware or you are trying to pretend to be unaware of what you were doing in this thread...):
"If you don't like brutal honesty then that's your problem."
"Do you get a kick out of bullying autistic people?"
"You appear you also can not take criticism."

With all of these statements you are attributing bad things to my character (and that was uncalled for). Although you're using qualifiers like "You appear", "If" and a question mark to pretend you're fair, it's clear that this is toxic behaviour (thanks again for introducing the term).  

> I will never be using this software and i am glad not to be apart of this "community".

I'm very hopeful this is true. You're wasting everyone's time, which I suspected very early on. Just look at all the other open and closed issues for Browsh on github. You've been the only unfriendly person so far, everyone else behaved constructively. All other interactions have been pleasant. You're not missed.

**Comment by SAUCYSOUP76** [comment]
@tobimensch you chose to twist what i said, take it out of context and misinterpret what i type. This is on you as i was speaking of myself and my own experience. And you took offense of what i typed as a personal attack on yourself which it was not.

**Comment by tobimensch** [comment]
@SAUCYSOUP76 
> you chose to twist what i said, take it out of context and misinterpret what i type

Either you've trouble expressing your true thoughts in text, or you're grossly negligent in what you write, without giving any thought whatsoever about how the message will and could be perceived by others. Or you're secretely trying to get a rise out of people, while acting like you're an innocent angel.

> This is on you as i was speaking of myself and my own experience.

You didn't make that clear in any way (you claimed that later to justify yourself, but that's something else). And even if this were true, there's no need to use a strong word like "horrible", it should be clear to any sane person, that this is insulting (and at the very least annoying) to the people that have put many hours into the project. You're trying to justify your behaviour by twisting everything around in such a way so that only the other people (in this case me) are the ones viewing everything wrongly or doing you wrong. Nobody tried to do you wrong, and you pissed on the project with your first reply to @tombh. You'll never be able to realize that though, because you seem to be oblivious to what courtesy is. And then you wonder why you get called out on it and play the victim.

Just a reminder: Github is a place for working together, it's not meant for reviewing and giving personal opinions on software. If you want to do that, start a blog, youtube channel, or go on a software rating website, and you can piss on Browsh there to your liking. We even tried to be helpful with your issue by making suggestions and providing information, but instead of saying "Thank you", like would be appropriate, you keep spreading your pissy thoughts nobody cares about.

> And you took offense of what i typed as a personal attack on yourself which it was not.

Are you lying to yourself, or do you really believe the words that you're writing? You asked me multiple questions that were laced with innuendo. They definitely were sneaky personal attacks. Don't try to act like an innocent lamb. I did return the favour and call you out on your bullshit.
