### ISSUE TITLE
Browsh cant be run on Raspbian due to lacking of Firefox 57+

### ISSUE THREAD

**Issue by misaalanshori** [browsh-org/browsh#271]
I ran browsh on my raspberry pi running raspbian and I got this error:
pi@raspberrypi:~ $ browsh
Installed Firefox version 52.9.0 is too old. Firefox 57 or newer is needed.

but when I try to upgrade firefox-esr I get this error:
pi@raspberrypi:~ $ sudo apt upgrade firefox-esr
Reading package lists... Done
Building dependency tree
Reading state information... Done
firefox-esr is already the newest version (52.9.0esr-1~deb9u1).

is it possible to use version 52.9.0 instead of 57?

**Comment by svonidze** [comment]
As of today v52.9.0 of firefox-esr is the latest working version on the standard Raspbian (that is which OS your pi is running on, I guess), see this thread https://raspberrypi.stackexchange.com/questions/75463/firefox-57-on-a-raspberry-pi
Shortly: Firefox is working on Ubuntu Mate 18.04 but not on Raspbian.

PS I recommend to change the issue title to something link: Browsh cant be run on Raspbian due to lacking of Firefox 57 or higher

**Comment by misaalanshori** [comment]
are there any reason why browsh cant use the older version?

**Comment by svonidze** [comment]
Obviously it uses some new functionally/API which was brought in the latest versions. But I have no knowledge what it is exactly.

**Comment by misaalanshori** [comment]
Closing issue, I can't do anything because rpi zero doesn't have Ubuntu and it probably will run slow on the rpi zero
