### ISSUE TITLE
Feature Request: replace google as default serach engine

### ISSUE THREAD

**Issue by git001** [browsh-org/browsh#281]
Please can you replace the default search engine to something else then google.

My suggestion is.

* https://duckduckgo.com/html?q=
* https://www.startpage.com/do/dsearch?query=

**Comment by tombh** [comment]
You can already do this with a setting in the config file: https://www.brow.sh/docs/config/

**Comment by 2br-2b** [comment]
Thank you so much for making this service! I really love Browsh!

I do agree that I would like it if Google were not the default search engine. Most people won't take the time to change the config file, and (at least in my opinion) it would be best to direct people towards a privacy respecting search engine rather than Google.
