### ISSUE TITLE
Rendering local html file 

### ISSUE THREAD

**Issue by ThangaAyyanar** [browsh-org/browsh#301]
any possible way to do above in mac?

**Comment by balsoft** [comment]
I can't do that in linux either. It tries to guess the domain name from file path for whatever reason. Prepending "file:///" doesn't help.

This issue seems to lack a lot of context that could be helpful to a developer, so I'll add it.

```
$ browsh --version                                        
1.5.2
```

Things I tried to render a local file:

```
$ browsh file.html
$ browsh ~/file.html
$ browsh file:///home/$USER/file.html
```

What somewhat "worked" (though I'd prefer to solve it another way):
```
$ caddy -root ~ & browsh http://localhost:2015/file.html
```

I'm using the above way for now, but it's really not a proper solution.

**Comment by ChaiTRex** [comment]
It seems like this is being dealt with in #76.

**Comment by tombh** [comment]
Closing fo #76

**Comment by tombh** [comment]
Closing fo #76

**Comment by adamency** [comment]
Hi @balsoft, I know the topic here is about a local html file, but you seem to be saying that `browsh` will correctly connect to a `localhost` address on your end when everywhere else people seem to say that it's the same problem, `browsh` simply won't reach a `localhost` address just as it won't for `file:///`:

- #456 specifically mentions the issue where @tombh says it is the same problem.
- `browsh` won't connect to any `localhost:X` url on my system.

So would you mind expalining, if you know, why it works for you in this case ? Thanks in advance.
