### ISSUE TITLE
Windows: "dial tcp 127.0.0.1:2828: connectex: No connection could be made"

### ISSUE THREAD

**Issue by tombh** [browsh-org/browsh#32]
I don't how popular running Browsh on Windows is? But we might as well have it working if it's possible. At the moment Firefox crashes during boot, I don't know why.

Of course Windows users, as I suspect most users, will use Browsh over Mosh/SSH, where Browsh runs on a Linux VM.

**Comment by tombh** [comment]
As a user on Twitter reports, the issue seems to be;

> dial tcp 127.0.0.1:2828: connectex: No connection could be made because the target machine actively refused it.

Which is Firefox's Marionette RPC. So this could be a port permissions error on Windows?

**Comment by dertuxmalwieder** [comment]
For me, `browsh` starts fine but crashes instantly after Firefox has been started:

    panic: runtime error: invalid memory address or nil pointer dereference◙[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4b4cdd]◙◙goroutine 19 [running]:◙os.(*Process).signal(0x0, 0x7cd560, 0x91c3c8, 0xc0422b4070, 0x0)◙    .go:58 +0x2d◙(0x0, , :◙
    C:\>

Sometimes it manages to display the "waiting for Firefox to connect" screen, at least.

Windows 10, Firefox 64 Bit.

**Comment by tombh** [comment]
Thanks for extra info

**Comment by janmechtel** [comment]
Same herein Windows 10, Firefox 64 Bit. 

1. I kill all firefox processes
2, Run browsh_1.2.3_windows_amd64

` dial tcp 127.0.0.1:2828: connectex: No connection could be made because the target machine actively refused it.`

3. Run browsh_1.2.3_windows_amd64 again:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4b4cdd]

goroutine 19 [running]:
os.(*Process).signal(0x0, 0x7d2540, 0x9233c8, 0xc042354070, 0x0)
	/home/travis/.gimme/versions/go1.10.3.linux.amd64/src/os/exec_windows.go:58 +


```

**Comment by jamespeace** [comment]
I have the same problem like @janmechtel on Windows7

**Comment by ParasDPain** [comment]
Same here! And as a windows user I'd prefer running it natively than wrapped in mosh tbh

**Comment by Structed** [comment]
Same here. I was using the `-firefox` option to specify the path for the x64 firefox executable.

When starting browsh via powershell, it opens a new Firefox window, spits out above panic message and the powershell process hangs. See screenshot
![image](https://user-images.githubusercontent.com/29922/42511896-69e7e3ae-8453-11e8-93a5-82f0384fdaf6.png)

**Comment by tombh** [comment]
@janmechtel Thanks for clarifying. (1) is really the main problem, (2) is just the fact that Browsh was unable to close Firefox in the first attempt.

I'm afraid this isn't a top priority for me to fix. Mainly as Browsh's main target is to be run on a remote server (in order to get the bandwidth savings for people on slow/expensive bandwidth locally). Also I haven't used windows in nearly 20 years now, so I'm not at all familiar with how to start debugging this.

But I'll certainly leave this issue open. I'd love to see this fixed. Maybe there's someone else that has more Windows experience that can help?

**Comment by tombh** [comment]
We may have found a fix! @morrah discovered that after seeing the "dial tcp" error Firefox was indeed running in the background. So he tried running Browsh again but this time with the `-use-existing-ff`.

In which we have a workaround. The idea being that you need to have headless Firefox running *before* starting Browsh. You can do this in 1 of 2 ways:

  1. Manually start your Firefox from the CLI with these arguments `--marionette --headless`.
  2. Run Browsh as you normally would so it starts Firefox, then wait for it crash.

You should now be able to run Browsh with the `-use-existing-ff` argument.

**Comment by tombh** [comment]
This should be formally fixed with a non-hacked solution as of v1.4.0. I'll reopen if this exact problem is reported again.

**Comment by Some-T** [comment]
Was having a look at this on Windows to see if I could get it working, noticed on virustotal.com it indicates the following: 

https://i.gyazo.com/b2510770f2475e95af63c30a41e8fd64.png  

Can anyone confirm if this is a false positive, please?

**Comment by tobimensch** [comment]
@Some-T 
It definitely is a false positive. PLease post in #67 about this and not here though.

**Comment by MarioColuzzi** [comment]
1) Opened CLI as Admin
2) Run browsh_1.4.13_windows_amd64.exe

I got this error:

Error reading Windows registry: The system cannot find the file specified.

**Comment by tobimensch** [comment]
@MarioColuzzi 
Looks more like issue #217 than this one! Please post there.

**Comment by sergeevabc** [comment]
So sad it does not work on Windows 7.

**Comment by tonybengue** [comment]
It seems to not work on Windows even with some flags added in the CLI

**Comment by AgentConDier** [comment]
Windows 10 Pro 1803; Firefox x64 66.0.6; browsh 1.5.0
Did anyone get this to work? As far as I know the problem is that when browsh tries to connect to firefox after starting it, firefox is not yet listening on port 2828 and windows refuses the connection, because if I try to connect to the same port after firefox has started, it works:
<pre><code>>curl localhost:2828
50:{"applicationType":"gecko","marionetteProtocol":3}</code></pre>
So the solution is supposed to be running `browsh.exe --firefox.use-existing`, but this just prints the `Waiting for a user-initiated Firefox instance to connect...` message and nothing happens. If I understood this right, this means that browsh is waiting for firefox to start, load the browsh addon and connect to the browsh process. But this will never happen, since the addon is not installed. As far as I know, there is no version of the addon available for manual install.
So is there any way to tell browsh to connect to a running firefox marionette so the addon can be installed? Or am I missing something?
Furthermore, you can not run browsh without --firefox.use-existing while firefox is running because this results in a
<pre><code>panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x4cc60d]

goroutine 35 [running]:
os.(*Process).signal(0x0, 0x9c18a0, 0xbe6470, 0xc0420fa020, 0x0)
	/home/travis/.gimme/versions/go1.10.5.linux.amd64/src/os/exec_windows.go:58 +0x2d
os.(*Process).Signal(0x0, 0x9c18a0, 0xbe6470, 0xc042057e80, 0x18)
	/home/travis/.gimme/versions/go1.10.5.linux.amd64/src/os/exec.go:129 +0x46
os.(*Process).kill(0x0, 0xc042045228, 0xc042057e80)
	/home/travis/.gimme/versions/go1.10.5.linux.amd64/src/os/exec_posix.go:54 +0x4a
os.(*Process).Kill(0x0, 0x3, 0x3)
	/home/travis/.gimme/versions/go1.10.5.linux.amd64/src/os/exec.go:114 +0x32
browsh/interfacer/src/browsh.startHeadlessFirefox()
	/home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:85 +0x3b9
created by browsh/interfacer/src/browsh.setupFirefox
	/home/travis/gopath/src/browsh/interfacer/src/browsh/firefox.go:288 +0x3c
</code></pre>
Incidentally, doing this managed to install the addon despite crashing. The addon then promptly connected to the waiting instance started with --firefox.use-existing which worked like a charm, so I guess I did get browsh to work. But this is tedious and hacky.

**Comment by jspraul** [comment]
Windows HOWTO, circa August 2019

Windows 10, Firefox 68, Brow.sh 1.64

1. Download the add-on from the bottom of the releases page (currently [browsh-1.6.4-an.fx.xpi](https://github.com/browsh-org/browsh/releases/download/v1.6.4/browsh-1.6.4-an.fx.xpi))
2. Open Firefox and install the add-on from the file
3. Run `"\Program Files\Mozilla Firefox\firefox.exe" --marionette --headless`
4. Run `browsh_1.6.4_windows_amd64.exe --firefox.use-existing`

Posted here because this issue is linked from the main website. I can add more details if necessary.

**Comment by MeetPing** [comment]
It's annoying to see a unfixed bug being closed all the time. The error I'm getting is concerning the registry and i want direct help into how this can be fixed.

**Comment by agent255** [comment]
same here @MeetPing Its realllly annoying

**Comment by 3prm3** [comment]
browsh just crashes instantly for me

**Comment by R727926** [comment]
failed to authenticate via web browser: Post "https://github.com/login/device/code": dial tcp 140.82.113.3:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
