### ISSUE TITLE
Inefficiencies in text_builder's sendRawText method

### ISSUE THREAD

**Issue by tobimensch** [browsh-org/browsh#46]
I looked through the code for a bit and this code in
webext/src/dom/text_builder.js
```  sendRawText() {
    // TODO:
    //   The presence of the `getScreenshotWithText()` and `setTimeout()` calls are a hack
    //   that I am unable to understand the reasoning for - unfortunately they came about
    //   by trial and error :( Without them the the returned raw text is largely empty.
    this.graphics_builder.getScreenshotWithText();
    setTimeout(() => {
      this.buildFormattedText();
      this._sendRawText();
    }, 200);
  }
```
I'm not sure how much this does slow down rendering pages, however the timeout makes it look like it's a slowdown by 200 ms at a minimum, which would be pretty significant, if true.

Since you didn't understand this behaviour, might this point to a bug in firefox? Did you try this mechanism in Chrome?

**Comment by tombh** [comment]
It certainly is a guaranteed lag of 200ms :( 

I haven't tried any of Browsh in Chrome yet, there's just too much Firefox-specific code.

The only clue I have to the cause of the bug is that's maybe to do with that fact that the webextension hides all text when it very first loads a page. Note that `this.buildFormattedText();` itself contains;
```js
this.graphics_builder.getScreenshotWithText();
this.graphics_builder.getScreenshotWithoutText();
```

So the flow of text rendering events is this; native page load renders text, webextension boots and hides all text, text parsing begins and a hack to show text is needed, then actual text parsing begins for real in `this.buildFormattedText();` which then does the only ever essentially needed show then hide of text.

Bear in mind that defaulting to having the native browser page rendered without text means that rendering of graphics frames is dramatically improved, by a factor of around 10.

**Comment by tobimensch** [comment]
I have an idea that also has some major disadvantages as it is probably a waste of resources (RAM, CPU) in itself, however that doesn't keep me from proposing it.

Did you think about using two renderers, one always rendering with (only) text (and to speed it up without graphics, if that is is possible at all) and one always rendering without text (so only graphics)? Everything else being the same, meaning they get the same user input etc.

In that case any inefficiencies caused by the hiding/showing of text should be eliminated.

This seems like a hacky solution (if it works at all). Just some food for thought.

**Comment by tobimensch** [comment]
I think the timeout (and other variables like it) should be configurable.

Then I could play around with it and I might figure out if the rendering problems become less with a higher timeout (than 200ms).

**Comment by tombh** [comment]
Already ahead of you there. The graphics and text renderers are already completely separate, sending frames updates independently.

I just realised, you know that `sendRawText()` is only for the HTTP Server? So this 200ms delay doesn't apply to the TTY client.

**Comment by tobimensch** [comment]
> I just realised, you know that sendRawText() is only for the HTTP Server? So this 200ms delay doesn't apply to the TTY client.

It makes sense now that I know it. :-)
