### ISSUE TITLE
It flashes and closes in windows.

### ISSUE THREAD

**Issue by midnio** [browsh-org/browsh#89]
After many tries, I can read the text at the bottom and it says "Waiting to connect Firefox" then it closes.

**Comment by Rav3nPL** [comment]
Looks like it need 32bit (!) firefox installed.

**Comment by Rav3nPL** [comment]
Duplicate to https://github.com/browsh-org/browsh/issues/87 ?

**Comment by dbenzhuser** [comment]
"Waiting to connect ..." indicates that it found the firefox executable, so I don't think this is related.

@midnio did you just double-click the browsh exe file? As this is a console application, it is better to open a new console window (Win key, then type cmd). This way, the window won't close when the program exits due to an error.
